import nodemailer from 'nodemailer';
import dotenv from 'dotenv';

dotenv.config();

// Get SMTP Configuration
const host = process.env.SMTP_HOST || 'smtp.gmail.com';
const port = parseInt(process.env.SMTP_PORT || '587');
const secure = port === 465; // SSL/TLS port
const user = process.env.SMTP_USER;
const pass = process.env.SMTP_PASS;

let transporter: nodemailer.Transporter | null = null;

if (user && pass) {
  // Initialize SMTP Transporter if credentials exist
  transporter = nodemailer.createTransport({
    host,
    port,
    secure,
    auth: { user, pass },
  });
} else {
  console.warn(
    '[Email Service] Warning: SMTP credentials (SMTP_USER/SMTP_PASS) are not set. Emails will be skipped in development.'
  );
}

interface ContactEmailPayload {
  name: string;
  email: string;
  subject: string;
  message: string;
}

/**
 * Send an email notification for contact form submissions.
 * Resilient to configuration or transmission issues.
 */
export const sendContactNotification = async (payload: ContactEmailPayload): Promise<void> => {
  try {
    const recipient = process.env.NOTIFICATION_EMAIL || 'AnkitMeena.fullstackDev@gmail.com';

    if (!transporter) {
      console.warn(
        `[Email Service] Skip sending notification email to ${recipient}. SMTP credentials are not set.`
      );
      return;
    }

    console.log(`[Email Service] Dispatching notification email to ${recipient}...`);

    const mailOptions = {
      from: `"Portfolio Contact Form" <${user}>`,
      to: recipient,
      replyTo: payload.email, // Allows clicking 'Reply' to respond directly to the user
      subject: `New Portfolio Message: ${payload.subject}`,
      html: `
        <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px; background-color: #ffffff;">
          <h2 style="color: #1e40af; border-bottom: 2px solid #1e40af; padding-bottom: 10px; margin-top: 0;">New Message Received</h2>
          <p style="font-size: 16px; color: #333333; line-height: 1.6;">You have received a new contact submission from your portfolio website.</p>
          
          <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
            <tr style="background-color: #f8fafc;">
              <td style="padding: 12px; font-weight: bold; color: #475569; width: 120px; border: 1px solid #e2e8f0;">Name:</td>
              <td style="padding: 12px; color: #0f172a; border: 1px solid #e2e8f0;">${payload.name}</td>
            </tr>
            <tr>
              <td style="padding: 12px; font-weight: bold; color: #475569; border: 1px solid #e2e8f0;">Email:</td>
              <td style="padding: 12px; color: #0f172a; border: 1px solid #e2e8f0;"><a href="mailto:${payload.email}" style="color: #3b82f6; text-decoration: none;">${payload.email}</a></td>
            </tr>
            <tr style="background-color: #f8fafc;">
              <td style="padding: 12px; font-weight: bold; color: #475569; border: 1px solid #e2e8f0;">Subject:</td>
              <td style="padding: 12px; color: #0f172a; border: 1px solid #e2e8f0; font-weight: 500;">${payload.subject}</td>
            </tr>
          </table>

          <div style="margin-top: 24px; padding: 16px; background-color: #f1f5f9; border-left: 4px solid #3b82f6; border-radius: 0 4px 4px 0;">
            <h4 style="margin: 0 0 8px 0; color: #475569; text-transform: uppercase; font-size: 12px; letter-spacing: 0.05em;">Message Body</h4>
            <p style="margin: 0; color: #0f172a; font-size: 15px; line-height: 1.6; white-space: pre-wrap;">${payload.message}</p>
          </div>

          <div style="margin-top: 30px; font-size: 12px; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 15px;">
            This email was auto-generated by your Portfolio Website backend.
          </div>
        </div>
      `,
    };

    const info = await transporter.sendMail(mailOptions);
    console.log('[Email Service] Notification email dispatched successfully. ID:', info.messageId);
  } catch (error) {
    console.error('[Email Service] Error encountered during email dispatch:', error);
    // Do not rethrow so database inserts are not blocked by email delivery errors
  }
};
